apiVersion: apps/v1
kind: Deployment
metadata:
  name: gekube-deployment
  labels:
    app: gekube
spec:
  replicas: 1
  template:
    metadata:
      name: gekube
      labels:
        app: gekube
    spec:
      containers:
      - name: gekube
        image: b:b878d9e98bcd98311e7e6727f8e692e1d2fcf166
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: gekube


---

apiVersion: v1
kind: Service
metadata:
  name: gekube-service
spec:
  selector:
    app: gekube
  ports:
    - port: 8080
  type: NodePort
  
  
